### ISSUE TITLE
How to exclude the protected folder from the builds-process

### ISSUE THREAD

**Issue by deepsoul** [flawyte/now-basic-auth#3]
Hi,
how can i exclude the protected folder from the build process. I added a nuxt project in the protected route, when i deploy to now there will be always an error that says

`Error: The lambda function size (104.57mb) exceeds the maximum size limit (50mb). Learn more: https://zeit.co/docs/v2/deployments/concepts/lambdas/#maximum-bundle-size`

But when i deploy the static site without those protected features it works without any problems

**Comment by flawyte** [comment]
Hi,

It depends on how you implemented Basic auth in your project. Did you do it using Vanilla js, or did you use something like Express, or [static-auth](https://github.com/flawyte/static-auth)?

Anyway I think your problem is related to the `config.includeFiles` property (in the `now.json` file) trying to bundle too much files, which gives a huge lambda. This is because last time I checked you couldn't serve files that were not bundled with the lambda – the lambda wouldn't be able to read them from the disk and you'd get a 404. For small projects it's ok since there aren't much files, but if you have big project this may be a problem indeed.

Maybe there's a better way to let Now lambdas access sibling files but right now I don't know it. This would require further investigation and tests.

**Comment by flawyte** [comment]
Quick update regarding my latest comment and the `config.includeFiles` property : as per my latest tests **this property isn't needed anymore** for the built lambdas to be able to read `.css`, `.html` or `.js` files on the disk.

This means that **you can safely remove it in most cases**. However if you're using Express together with the `@now/node-server` runtime and starting your server using `app.listen()` (similar to what the `node-express` example has shown until now), you'll have to do some modifications to your server ‒ but don't worry they are very trivial.

As such, **I've updated all three examples in this repository**, including the Express one, to remove all usages of the `config.includeFiles` property.

This should solve the OP's error, but if not please feel free to reopen.
