### ISSUE TITLE
Custom 404 page (404.html)

### ISSUE THREAD

**Issue by dennishzg** [flawyte/now-basic-auth#8]
First of all, thank you for this very useful repository. 👍 

I have a small question about the `now-basic-auth/node` code in this file: https://github.com/flawyte/now-basic-auth/blob/master/node/index.js .

(My entire website is password-protected and my output directory is called `dist` instead of `_static`)

How do i show a custom 404 page instead of the "404 Not Found" message (when authorized)?
https://github.com/flawyte/now-basic-auth/blob/86e9bdd5b6f39a8635fe2b01ec4273738961dfe8/node/index.js#L35

I want to show my 404.html file instead of the "404 Not Found" message. The file is located at /dist/404.html.
Vercel supports custom 404 pages via a 404.html file in the output directory. How can i use that feature together with your `now-basic-auth/node` code? Vercel should detect the 404.html file automatically right? I don't have to reference the /dist/404.html file in the index.js right? Do i have to remove the `handle404` part at line 33-36?:

```diff
// Serve files
-  return serve(req, res, () => {
-    res.statusCode = 404;
-    res.end('404 Not Found');
-  });
+  return serve(req, res);
```

**Comment by flawyte** [comment]
Hi @dennishzg 
No problem! My pleasure.

Since your entire website is password-protected and thus all requests go through the `index.js` file, even if your 404 html file follows Vercel's convention I don't see how it could be used automatically.

I don't see any other solution than to read the 404 page in the `index.js` file and returns its contents manually when the requested file can't be found. I haven't tried, but I'm thinking about something like this :

```node
const fs = require('fs');
const pathTo404Page = __dirname + '/dist/404.html';

// Serve files
return serve(req, res, () => {
  const html = fs.readFileSync(pathTo404Page, 'utf8');
  res.writeHead(404, {'Content-Type': 'text/html'});  
  res.write(html);  
  res.end();  
});
```

This should work if your file is located at `dist/404.html` and your `dist` directory is in the same directory as the `index.js` file. Otherwise, just change the `pathTo404Page` variable.

Let me know if that worked! :)

**Comment by dennishzg** [comment]
It worked! Thank you. 👍
